"""empty message

Revision ID: 2151ccb696db
Revises: 2ce4dd92fc99
Create Date: 2021-04-14 16:47:17.685003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2151ccb696db'
down_revision = '2ce4dd92fc99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ngoName', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('about', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ngo_email'), 'ngo', ['email'], unique=True)
    op.create_index(op.f('ix_ngo_ngoName'), 'ngo', ['ngoName'], unique=True)
    op.drop_index('ix_NGO_email', table_name='NGO')
    op.drop_index('ix_NGO_ngoName', table_name='NGO')
    op.drop_table('NGO')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NGO',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"NGO_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('ngoName', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('contact_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('about', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='NGO_pkey')
    )
    op.create_index('ix_NGO_ngoName', 'NGO', ['ngoName'], unique=True)
    op.create_index('ix_NGO_email', 'NGO', ['email'], unique=True)
    op.drop_index(op.f('ix_ngo_ngoName'), table_name='ngo')
    op.drop_index(op.f('ix_ngo_email'), table_name='ngo')
    op.drop_table('ngo')
    # ### end Alembic commands ###
