"""post tables

Revision ID: 577da079f832
Revises: 
Create Date: 2021-04-08 06:33:33.679387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577da079f832'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_code', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('longitude', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_category', sa.String(), nullable=False),
    sa.Column('item', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurantname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('cuisine', sa.String(length=45), nullable=True),
    sa.Column('weekdays', sa.String(length=10), nullable=True),
    sa.Column('weekends', sa.String(length=10), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_email'), 'restaurant', ['email'], unique=True)
    op.create_index(op.f('ix_restaurant_points'), 'restaurant', ['points'], unique=False)
    op.create_index(op.f('ix_restaurant_restaurantname'), 'restaurant', ['restaurantname'], unique=True)
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookedBy', sa.Integer(), nullable=True),
    sa.Column('bookedOn', sa.DateTime(), nullable=False),
    sa.Column('bookingOn', sa.DateTime(), nullable=False),
    sa.Column('num_of_seats', sa.Integer(), nullable=False),
    sa.Column('restaurant', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookedBy'], ['user.id'], ),
    sa.ForeignKeyConstraint(['restaurant'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant', sa.Integer(), nullable=True),
    sa.Column('item', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('availablility', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['item'], ['item.id'], ),
    sa.ForeignKeyConstraint(['restaurant'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    op.drop_table('booking')
    op.drop_index(op.f('ix_restaurant_restaurantname'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_points'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_email'), table_name='restaurant')
    op.drop_table('restaurant')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('item')
    op.drop_table('address')
    # ### end Alembic commands ###
