"""empty message

Revision ID: 65dc45fbe7b7
Revises: d3a5d0a3130c
Create Date: 2021-04-26 01:00:27.343620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65dc45fbe7b7'
down_revision = 'd3a5d0a3130c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('user_order', sa.Column('orderDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_order', 'orderDate')
    op.drop_column('user', 'points')
    # ### end Alembic commands ###
