"""empty message

Revision ID: 98f0ad322bc5
Revises: 17d113c970f5
Create Date: 2021-04-15 09:29:16.179848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f0ad322bc5'
down_revision = '17d113c970f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donatedBy', sa.Integer(), nullable=True),
    sa.Column('donatedTo', sa.Integer(), nullable=True),
    sa.Column('donatedItems', sa.String(length=200), nullable=True),
    sa.Column('donationRestaurant', sa.Integer(), nullable=True),
    sa.Column('donated', sa.Boolean(), nullable=True),
    sa.Column('donationDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donatedBy'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['donatedBy'], ['user.id'], ),
    sa.ForeignKeyConstraint(['donatedTo'], ['ngo.id'], ),
    sa.ForeignKeyConstraint(['donationRestaurant'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation')
    # ### end Alembic commands ###
