"""empty message

Revision ID: db86d2eb440b
Revises: 7a7fd86e784a
Create Date: 2021-04-25 20:10:38.965250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db86d2eb440b'
down_revision = '7a7fd86e784a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('locality', sa.String(), nullable=True))
    op.add_column('address', sa.Column('sub_locality', sa.String(), nullable=True))
    op.drop_column('address', 'longitude')
    op.drop_column('address', 'latitude')
    op.drop_column('address', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('address', sa.Column('latitude', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('longitude', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.drop_column('address', 'sub_locality')
    op.drop_column('address', 'locality')
    # ### end Alembic commands ###
